language: php
sudo: false

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm
  - nightly

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly

install:
  - composer self-update
  - composer install --no-interaction

script:
  - ./vendor/bin/phpcs --standard=phpcs.xml lib
